######################################################################
# Automatically generated by qmake (2.01a) Fr. Okt 2 16:15:33 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /home/user/Desktop/zumBasteln/USBgLCD/qt4paint_usbglcd/. .

# Input
HEADERS += paintfield.h usbglcd.h
SOURCES += main.cpp paintfield.cpp usbglcd.cpp
LIBS += -lusb